config/routes.rb
Rails.application.routes.draw do

  get '/', to: 'site#home', as: :home

  get '/text_inspections/new', to: 'text_inspections#new', as: :new

  post '/text_inspections', to: 'text_inspections#create', as: :create

  get '/text_inspections/results', to: 'text_inspections#results', as: :results

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
	def home
		render 'home'
	end
end

app/controllers/text_inspections_controller.rb
class TextInspectionsController < ApplicationController
	def new
		render 'new'
	end
	def create
		@text = params[:text_inspection][:user_text]
		@word_count = @text.split(" ").length
		@minutes_reading = @word_count/275
		@conclusion = "The estimated time of reading is #{@minutes_reading} minutes."
		@frequency = Hash.new(0)
		@scanned = @text.downcase.scan(/\b[a-z]{1,30}\b/).to_a {|word| @frequency[word] = @frequency[word] + 1}
		@sorted = @scanned.sort_by {|key, value| value }.reverse
		@most_frequent_words = @sorted[0..9].join(", ")
		render "results"
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/helpers/text_inspections_helper.rb
module TextInspectionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WordCentral</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/site/home.html.erb
<h1>Word Central</h1>

<p>Your destination for text utilities.</p>

app/views/text_inspections/new.html.erb
<h1>Word Central</h1>

<h2>Submit text for inspection</h2>

<form action="/text_inspections" method="post">
	<div>
		<label for="text_inspection_user_text">Text</label>
		<textarea name="text_inspection[user_text]" id="text_inspection_user_text"></textarea>
	</div>
	<button type="submit">Submit text</button>
	<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
</form>

app/views/text_inspections/results.html.erb
<p>You wrote: <%= @word_count %> words.</p>
<br>
<p>
	Original input:
	<br>
	<%= @text %>
</p>
<br>
<%= @conclusion %>

<p>Return to <%= link_to 'Home', home_path %></p>
<br>
<p>
	The 10 most frequent words in this text are:
	<br>
	<%= @most_frequent_words %>
</p>